"""empty message

Revision ID: 844a72ad2047
Revises: 35c185bcf61e
Create Date: 2020-12-09 10:53:37.877518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844a72ad2047'
down_revision = '35c185bcf61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('removed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'removed')
    # ### end Alembic commands ###
