"""empty message

Revision ID: ba6db4db94aa
Revises: 2f7bc898e7e3
Create Date: 2020-12-07 14:50:55.357012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6db4db94aa'
down_revision = '2f7bc898e7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('removed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'removed')
    # ### end Alembic commands ###
