"""empty message

Revision ID: 06d1a0348f88
Revises: 483e9d6d8522
Create Date: 2020-12-03 11:50:07.837488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06d1a0348f88'
down_revision = '483e9d6d8522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('routineId', sa.Integer(), nullable=True),
    sa.Column('workoutId', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['routineId'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workoutId'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('userReports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userReports',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userReports_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('routineId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('workoutId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routineId'], ['routines.id'], name='userReports_routineId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='userReports_userId_fkey'),
    sa.ForeignKeyConstraint(['workoutId'], ['workouts.id'], name='userReports_workoutId_fkey'),
    sa.PrimaryKeyConstraint('id', name='userReports_pkey')
    )
    op.drop_table('user_reports')
    # ### end Alembic commands ###
