"""empty message

Revision ID: 1197cc82fb58
Revises: 06d1a0348f88
Create Date: 2020-12-03 11:54:21.468098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1197cc82fb58'
down_revision = '06d1a0348f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routineId', sa.Integer(), nullable=False),
    sa.Column('tagId', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['routineId'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('routineTags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routineTags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"routineTags_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('routineId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tagId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['routineId'], ['routines.id'], name='routineTags_routineId_fkey'),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], name='routineTags_tagId_fkey'),
    sa.PrimaryKeyConstraint('id', name='routineTags_pkey')
    )
    op.drop_table('routine_tags')
    # ### end Alembic commands ###
