"""empty message

Revision ID: 2f7bc898e7e3
Revises: f03a22dff80c
Create Date: 2020-12-03 17:24:02.995131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7bc898e7e3'
down_revision = 'f03a22dff80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('routine_tags_routineId_fkey', 'routine_tags', type_='foreignkey')
    op.create_foreign_key(None, 'routine_tags', 'routines', ['routineId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routine_tags', type_='foreignkey')
    op.create_foreign_key('routine_tags_routineId_fkey', 'routine_tags', 'users', ['routineId'], ['id'])
    # ### end Alembic commands ###
