"""empty message

Revision ID: 76103743143a
Revises: 0a66b1ea0744
Create Date: 2020-12-13 16:05:54.026450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76103743143a'
down_revision = '0a66b1ea0744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('removed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'removed')
    # ### end Alembic commands ###
