"""empty message

Revision ID: 4b1035524c18
Revises: 844a72ad2047
Create Date: 2020-12-09 13:18:19.360695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1035524c18'
down_revision = '844a72ad2047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('photo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'photo_url')
    # ### end Alembic commands ###
