"""empty message

Revision ID: f03a22dff80c
Revises: d93b03ce76f6
Create Date: 2020-12-03 17:21:26.842521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03a22dff80c'
down_revision = 'd93b03ce76f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routine_tags', 'routineId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('routine_tags_routineId_fkey', 'routine_tags', type_='foreignkey')
    op.create_foreign_key(None, 'routine_tags', 'users', ['routineId'], ['id'])
    op.drop_column('routine_tags', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_tags', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'routine_tags', type_='foreignkey')
    op.create_foreign_key('routine_tags_routineId_fkey', 'routine_tags', 'routines', ['routineId'], ['id'])
    op.alter_column('routine_tags', 'routineId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
