"""empty message

Revision ID: 0a66b1ea0744
Revises: aa506496a272
Create Date: 2020-12-12 15:32:13.489656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a66b1ea0744'
down_revision = 'aa506496a272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('removed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'removed')
    # ### end Alembic commands ###
