"""empty message

Revision ID: c4ffb136c74c
Revises: ffdc0a98111c
Create Date: 2020-12-03 09:49:17.246208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ffb136c74c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('faceBook', sa.String(), nullable=True))
    op.add_column('users', sa.Column('insta', sa.String(), nullable=True))
    op.add_column('users', sa.Column('youTube', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'youTube')
    op.drop_column('users', 'insta')
    op.drop_column('users', 'faceBook')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
