"""empty message

Revision ID: aa506496a272
Revises: 4b1035524c18
Create Date: 2020-12-12 12:34:58.622147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa506496a272'
down_revision = '4b1035524c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sessions', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
