"""empty message

Revision ID: f79d4797f894
Revises: 75ba1411200c
Create Date: 2020-12-03 11:17:05.259769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79d4797f894'
down_revision = '75ba1411200c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.Integer(), nullable=False),
    sa.Column('workoutId', sa.Integer(), nullable=False),
    sa.Column('sets', sa.String(), nullable=True),
    sa.Column('reps', sa.String(), nullable=True),
    sa.Column('setType', sa.String(), nullable=True),
    sa.Column('tempo', sa.String(), nullable=True),
    sa.Column('rest', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('additionalComments', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sessionId'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['workoutId'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercises')
    # ### end Alembic commands ###
